Update Pertanggal 06 Desember 2021 14:49:12

diff --git a/Programming/WebFrontEnd/vendor/nesbot/carbon/.github/workflows/tests.yml b/Programming/WebFrontEnd/vendor/nesbot/carbon/.github/workflows/tests.yml
--- a/Programming/WebFrontEnd/vendor/nesbot/carbon/.github/workflows/tests.yml
+++ b/Programming/WebFrontEnd/vendor/nesbot/carbon/.github/workflows/tests.yml
@@ -59,7 +59,11 @@ jobs:
           - php: 8.0
             laravel: true
 
-    name: ${{ matrix.laravel && 'Laravel compatibility - ' || '' }}${{ matrix.coverage && 'Coverage - ' || '' }}PHP ${{ matrix.php }} - ${{ matrix.setup || 'stable' }} - ubuntu
+          - php: 8.0
+            laravel: true
+            classmap-authoritative: true
+
+    name: ${{ matrix.laravel && 'Laravel compatibility - ' || '' }}${{ matrix.classmap-authoritative && 'classmap-authoritative - ' || '' }}${{ matrix.coverage && 'Coverage - ' || '' }}PHP ${{ matrix.php }} - ${{ matrix.setup || 'stable' }} - ubuntu
 
     steps:
       - uses: actions/checkout@v2
@@ -74,7 +78,8 @@ jobs:
 
       - name: Install locales
         run: |
-          sudo apt-get update && sudo apt-get install tzdata locales -y && sudo locale-gen fr_FR.UTF-8 sr_ME.UTF-8 ar_AE.UTF-8 zh_TW.UTF-8 zh_CN.UTF-8 yo_NG.UTF-8 en_US.UTF-8
+          sudo apt-get update || apt --fix-broken install || echo 'Apt failure ignored'
+          sudo apt-get install tzdata locales -y && sudo locale-gen fr_FR.UTF-8 sr_ME.UTF-8 ar_AE.UTF-8 zh_TW.UTF-8 zh_CN.UTF-8 yo_NG.UTF-8 en_US.UTF-8 || echo 'Apt failure ignored'
 
       - name: Setup Memcached
         if: matrix.laravel
@@ -87,7 +92,7 @@ jobs:
             composer remove --no-update kylekatarnls/multi-tester --no-interaction;
           fi;
           ${{ matrix.php >= 8.1 && 'composer require --no-update phpunit/phpunit:^8.5.14 --no-interaction;' || '' }}
-          composer update --prefer-dist --no-progress --prefer-${{ matrix.setup || 'stable' }} ${{ matrix.php >= 8.1 && '--ignore-platform-req=php' || '' }};
+          composer update --prefer-dist --no-progress --prefer-${{ matrix.setup || 'stable' }} ${{ matrix.php >= 8.1 && '--ignore-platform-req=php' || '' }} ${{ matrix.classmap-authoritative && '--classmap-authoritative' || '' }};
 
       - name: Run test suite
         run: |
